/**
 * Iron Law 2.42 integration gate — every ProductTestPanel marked
 * available=true must have a thumbnail PNG on disk at the expected
 * path.
 *
 * The thumbnail is generated by scripts/ingest-coa-pdfs.mjs (P1B/P1C)
 * via pdftoppm + sharp. The /verify/[slug] route renders each
 * TestCard's thumbPath as the small COA preview; if the file is
 * missing, the customer sees a broken-image icon — a customer-
 * visible regression that this gate catches in CI.
 *
 * Passes vacuously when productTestPanels is empty (pre-P1D state).
 */
import { describe, expect, it } from "vitest";
import { promises as fs } from "node:fs";
import path from "node:path";

import { productTestPanels } from "@/lib/content/coa";

const REPO_ROOT = process.cwd();

describe("Iron Law 2.42 — COA thumbnail availability gate", () => {
  it("every available test has its thumbnail PNG on disk", async () => {
    const missing: Array<{ slug: string; test: string; expected: string }> = [];
    const tests = ["purity", "sterility", "endotoxin", "heavyMetals"] as const;
    for (const [slug, panel] of Object.entries(productTestPanels)) {
      for (const testKey of tests) {
        const test = panel[testKey];
        if (!test.available) continue;
        if (!test.thumbPath) {
          missing.push({
            slug,
            test: testKey,
            expected: "(no thumbPath field)",
          });
          continue;
        }
        const fsPath = path.join(
          REPO_ROOT,
          "public",
          test.thumbPath.replace(/^\//, ""),
        );
        try {
          const stat = await fs.stat(fsPath);
          expect(stat.size).toBeGreaterThan(1000);
        } catch {
          missing.push({ slug, test: testKey, expected: fsPath });
        }
      }
    }
    if (missing.length > 0) {
      const msg = missing
        .map((m) => `  - ${m.slug}/${m.test}: missing ${m.expected}`)
        .join("\n");
      throw new Error(
        `Iron Law 2.42 — ${missing.length} thumbnail(s) missing from public/coa-thumbnails/:\n${msg}\n` +
          "Re-run scripts/ingest-coa-pdfs.mjs to regenerate.",
      );
    }
    expect(missing).toHaveLength(0);
  });
});
