-- Generated from site/lib/catalog-seed.ts.
-- Regenerate with: node --experimental-strip-types scripts/generate-catalog-seed.mjs
insert into public.products (
  id,
  slug,
  sku,
  name,
  summary,
  category,
  format,
  storage,
  price_cents,
  research_use_only,
  active,
  documentation_status,
  availability_status,
  visible_to_approved
)
values
  (
    'bpc-157-5mg',
    'bpc-157-5mg',
    'MGX-REC-BPC-005',
    'BPC-157 5mg',
    'Recovery-line peptide record with visible lot context, quality framing, and signed-in catalog pricing.',
    'reference',
    'Lyophilized powder',
    '2-8 C unopened. Controlled cold storage after intake.',
    4900,
    true,
    true,
    'coa-ready',
    'requestable',
    true
  ),
  (
    'bpc-157-tb-500-5mg-5mg',
    'bpc-157-tb-500-5mg-5mg',
    'MGX-REC-BT5-010',
    'BPC-157 + TB-500 5mg/5mg',
    'Blend reference entry with visible pricing, conservative copy, and gated document release.',
    'reference',
    'Lyophilized powder',
    '2-8 C unopened. Cold-chain logging required after receipt.',
    7900,
    true,
    true,
    'document-review',
    'requestable',
    true
  ),
  (
    'cjc-1295-no-dac-5mg',
    'cjc-1295-no-dac-5mg',
    'MGX-GH-CJC-005',
    'CJC-1295 No DAC 5mg',
    'GH-pathway peptide listing with visible pricing, batch code, and conservative research framing.',
    'analytical',
    'Lyophilized powder',
    '2-8 C unopened. Protect from heat and uncontrolled rehandling.',
    6900,
    true,
    true,
    'coa-ready',
    'requestable',
    true
  ),
  (
    'cjc-1295-ipamorelin-5mg-5mg',
    'cjc-1295-ipamorelin-5mg-5mg',
    'MGX-GH-CJI-010',
    'CJC-1295 + Ipamorelin 5mg/5mg',
    'Signed-in blend listing with visible price, blend record status, and conservative transfer language.',
    'analytical',
    'Lyophilized powder',
    '2-8 C unopened. Maintain internal blend handling logs.',
    8200,
    true,
    true,
    'document-review',
    'requestable',
    true
  ),
  (
    'ipamorelin-5mg',
    'ipamorelin-5mg',
    'MGX-GH-IPA-005',
    'Ipamorelin 5mg',
    'GH-pathway single-compound listing with clear pricing, specs, and batch lookup context.',
    'analytical',
    'Lyophilized powder',
    '2-8 C unopened. Controlled laboratory storage required.',
    6300,
    true,
    true,
    'coa-ready',
    'requestable',
    true
  ),
  (
    'semax-5mg',
    'semax-5mg',
    'MGX-NEU-SMX-005',
    'Semax 5mg',
    'Neuropeptide listing with visible price, archive-friendly batch info, and private-catalog tone.',
    'reference',
    'Lyophilized powder',
    '2-8 C unopened. Light-sensitive storage controls recommended.',
    5900,
    true,
    true,
    'coa-ready',
    'limited-review',
    true
  ),
  (
    'selank-5mg',
    'selank-5mg',
    'MGX-NEU-SEL-005',
    'Selank 5mg',
    'Neuropeptide storefront listing with lot context, pricing, and conservative documentation language.',
    'reference',
    'Lyophilized powder',
    '2-8 C unopened. Track secondary containment after receipt.',
    6100,
    true,
    true,
    'document-review',
    'limited-review',
    true
  ),
  (
    'dihexa-5mg',
    'dihexa-5mg',
    'MGX-NEU-DHX-005',
    'Dihexa 5mg',
    'Batch-coded neuropeptide listing with visible pricing, support docs, and verification framing.',
    'reference',
    'Lyophilized powder',
    '2-8 C unopened. Monitor storage state through internal lab logs.',
    9500,
    true,
    true,
    'coa-ready',
    'limited-review',
    true
  ),
  (
    'ghk-cu-50mg-100mg',
    'ghk-cu-50mg-100mg',
    'MGX-COP-GHK-050100',
    'GHK-Cu 50mg / 100mg',
    'Variant storefront listing with visible pricing, multi-strength context, and lot-linked documentation.',
    'handling',
    'Lyophilized powder',
    '2-8 C unopened. Track variant handling under the same batch log.',
    7200,
    true,
    true,
    'coa-ready',
    'limited-review',
    true
  ),
  (
    'ghk-cu-bpc-157-tb-500-blend',
    'ghk-cu-bpc-157-tb-500-blend',
    'MGX-COP-GBT-TRI',
    'GHK-Cu + BPC-157 + TB-500 Blend',
    'Tri-blend storefront record with visible price, lot framing, and conservative review language.',
    'handling',
    'Lyophilized powder',
    '2-8 C unopened. Maintain blend-specific intake records.',
    10900,
    true,
    true,
    'document-review',
    'limited-review',
    true
  ),
  (
    'hgh-frag-176-191-5mg',
    'hgh-frag-176-191-5mg',
    'MGX-ML-HGF-005',
    'HGH Frag 176-191 5mg',
    'Metabolic-line listing with pricing, specs, and batch-level verification context.',
    'analytical',
    'Lyophilized powder',
    '2-8 C unopened. Record cold storage after laboratory intake.',
    6800,
    true,
    true,
    'coa-ready',
    'limited-review',
    true
  ),
  (
    'mazdutide-10mg',
    'mazdutide-10mg',
    'MGX-ML-MAZ-010',
    'Mazdutide 10mg',
    'Metabolic-line storefront listing with visible pricing, lot context, and conservative catalog copy.',
    'analytical',
    'Lyophilized powder',
    '2-8 C unopened. Protect from uncontrolled thaw cycles.',
    9800,
    true,
    true,
    'document-review',
    'limited-review',
    true
  ),
  (
    'mots-c-10mg-40mg',
    'mots-c-10mg-40mg',
    'MGX-ML-MOT-010040',
    'MOTS-c 10mg / 40mg',
    'Variant metabolic listing with visible price, two-strength context, and batch-linked support detail.',
    'analytical',
    'Lyophilized powder',
    '2-8 C unopened. Record variant selection before downstream handling.',
    8900,
    true,
    true,
    'coa-ready',
    'limited-review',
    true
  ),
  (
    'foxo4-dri-10mg',
    'foxo4-dri-10mg',
    'MGX-ML-FOX-010',
    'FOXO4-DRI 10mg',
    'Longevity-line storefront listing with visible price, clear specs, and review-driven batch framing.',
    'analytical',
    'Lyophilized powder',
    '2-8 C unopened. Keep storage logs with the batch record.',
    11900,
    true,
    true,
    'document-review',
    'limited-review',
    true
  ),
  (
    'humanin-10mg',
    'humanin-10mg',
    'MGX-ML-HUM-010',
    'Humanin 10mg',
    'Signed-in longevity-line listing with pricing, batch context, and verification-aware copy.',
    'analytical',
    'Lyophilized powder',
    '2-8 C unopened. Preserve chain-of-custody records after receipt.',
    7600,
    true,
    true,
    'coa-ready',
    'limited-review',
    true
  )
on conflict (id) do update
set slug = excluded.slug,
    sku = excluded.sku,
    name = excluded.name,
    summary = excluded.summary,
    category = excluded.category,
    format = excluded.format,
    storage = excluded.storage,
    price_cents = excluded.price_cents,
    research_use_only = excluded.research_use_only,
    active = excluded.active,
    documentation_status = excluded.documentation_status,
    availability_status = excluded.availability_status,
    visible_to_approved = excluded.visible_to_approved,
    updated_at = timezone('utc', now());
